# Generated by Django 6.0 on 2026-04-01 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Чемпионат России 2025', max_length=200, verbose_name='Название соревнования')),
                ('date', models.DateField(help_text='Когда состоялись соревнования', verbose_name='Дата проведения')),
                ('protocol_file', models.FileField(blank=True, help_text='Загрузите PDF файл с протоколом', null=True, upload_to='protocols/', verbose_name='Протокол PDF')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Автоматически заполняется при загрузке', verbose_name='Дата загрузки')),
            ],
            options={
                'verbose_name': 'Соревнование',
                'verbose_name_plural': 'Соревнования',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Плавание в ластах - 100 м', max_length=100, unique=True, verbose_name='Название дистанции')),
                ('gender', models.CharField(choices=[('M', 'Мужчины'), ('F', 'Женщины')], help_text='Мужчины или Женщины', max_length=1, verbose_name='Пол')),
                ('distance_meters', models.IntegerField(default=0, help_text='Длина дистанции в метрах (50, 100, 200...)', verbose_name='Дистанция (метры)')),
                ('is_relay', models.BooleanField(default=False, help_text='Отметьте, если это эстафета', verbose_name='Эстафета')),
            ],
            options={
                'verbose_name': 'Дистанция',
                'verbose_name_plural': 'Дистанции',
                'ordering': ['distance_meters', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Фамилия Имя Отчество', max_length=150, verbose_name='ФИО спортсмена')),
                ('birth_year', models.IntegerField(blank=True, help_text='Например: 2005', null=True, verbose_name='Год рождения')),
                ('team', models.CharField(blank=True, help_text='Например: Томская область', max_length=100, null=True, verbose_name='Команда/Регион')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Когда спортсмен впервые появился в базе', verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Спортсмен',
                'verbose_name_plural': 'Спортсмены',
                'ordering': ['full_name'],
                'unique_together': {('full_name', 'birth_year')},
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.IntegerField(blank=True, help_text='Занятое место (1, 2, 3...)', null=True, verbose_name='Место')),
                ('rank', models.CharField(blank=True, help_text='МС, КМС, ЗМС и т.д.', max_length=10, null=True, verbose_name='Разряд')),
                ('result_time', models.CharField(help_text='Время: 00:16,46', max_length=20, verbose_name='Результат')),
                ('final_result', models.CharField(blank=True, help_text='Если был финал', max_length=20, null=True, verbose_name='Результат финала')),
                ('best_result', models.CharField(blank=True, help_text='Лучший из заплывов', max_length=20, null=True, verbose_name='Лучший результат')),
                ('normative', models.CharField(blank=True, help_text='На какой норматив проплыл', max_length=10, null=True, verbose_name='Норматив')),
                ('points', models.IntegerField(default=0, help_text='Количество очков за этот результат', verbose_name='Очки')),
                ('is_relay', models.BooleanField(default=False, help_text='Эстафетный заплыв', verbose_name='Эстафета')),
                ('is_manual_timing', models.BooleanField(default=False, help_text='Ручное время (не автоматическое)', verbose_name='Ручной хронометраж')),
                ('parsed_at', models.DateTimeField(auto_now_add=True, help_text='Когда результат добавлен в базу', verbose_name='Дата парсинга')),
                ('athlete', models.ForeignKey(help_text='Кто показал результат', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='laba_1.athlete', verbose_name='Спортсмен')),
                ('competition', models.ForeignKey(help_text='На каких соревнованиях', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='laba_1.competition', verbose_name='Соревнование')),
                ('distance', models.ForeignKey(help_text='Какая дистанция', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='laba_1.distance', verbose_name='Дистанция')),
            ],
            options={
                'verbose_name': 'Результат',
                'verbose_name_plural': 'Результаты',
                'ordering': ['competition', 'distance', 'place'],
                'unique_together': {('athlete', 'competition', 'distance')},
            },
        ),
    ]
