# Generated by Django 6.0 on 2026-04-16 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laba_1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='removed',
            field=models.BooleanField(default=False, help_text='True если запись удалена', verbose_name='Удалено'),
        ),
    ]
