# Generated by Django 6.0 on 2026-04-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laba_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distance',
            name='gender',
            field=models.CharField(choices=[('M', 'Мужчины'), ('F', 'Женщины'), ('X', 'Смешанная')], help_text='Мужчины или Женщины', max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='distance',
            name='name',
            field=models.CharField(help_text='Например: Плавание в ластах - 100 м', max_length=100, verbose_name='Название дистанции'),
        ),
        migrations.AlterUniqueTogether(
            name='distance',
            unique_together={('name', 'gender')},
        ),
    ]
