# Generated by Django 6.0 on 2026-06-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laba_1', '0003_usergroup_activitylog_emailconfirmation_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='name',
            field=models.CharField(choices=[('viewer', 'Просмотр (неавторизованный)'), ('Authorized', 'Пользователь'), ('admin', 'Администратор')], max_length=50, unique=True, verbose_name='Название группы'),
        ),
    ]
