# Generated by Django 6.0.4 on 2026-04-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laba_1', '0004_remove_result_is_relay_alter_result_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='removed',
            field=models.BooleanField(default=False, help_text='Отметьте True для мягкого удаления объекта', verbose_name='Удален'),
        ),
    ]
