# Generated by Django 6.0 on 2026-06-03 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laba_1', '0004_alter_usergroup_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='name',
            field=models.CharField(choices=[('viewer', 'Просмотр (неавторизованный)'), ('Authorized', 'Пользователь'), ('Coach', 'Тренер'), ('admin', 'Администратор')], max_length=50, unique=True, verbose_name='Название группы'),
        ),
    ]
