# Generated by Django 6.0 on 2026-06-03 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laba_1', '0005_alter_usergroup_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар (URL)'),
        ),
    ]
